apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: mysql-sc-azurefile 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi

